/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make changes to this file directly.
// Updates are done via the router configuration.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRoute } from './routes/__root'

const IndexImport = createFileRoute('/')()
const BoxesImport = createFileRoute('/boxes')()
const MessageMessageIdImport = createFileRoute('/message/$messageId')()

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/boxes': {
      preLoaderRoute: typeof BoxesImport
      parentRoute: typeof rootRoute
    }
    '/message/$messageId': {
      preLoaderRoute: typeof MessageMessageIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index').then((d) => d.Route))

const BoxesRoute = BoxesImport.update({
  id: '/boxes',
  path: '/boxes',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/boxes').then((d) => d.Route))

const MessageMessageIdRoute = MessageMessageIdImport.update({
  id: '/message/$messageId',
  path: '/message/$messageId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/message/$messageId').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/boxes': {
      preLoaderRoute: typeof BoxesImport
      parentRoute: typeof rootRoute
    }
    '/message/$messageId': {
      preLoaderRoute: typeof MessageMessageIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  BoxesRoute,
  MessageMessageIdRoute,
])

export default routeTree
